#!/usr/bin/env bash

currdir=$(dirname $0)

mkdir -p ~/.workspace/databases/mysql
echo "need your password to make workspace executable"
sudo chown -R $(whoami) "$currdir"
sudo chmod 755 "$currdir"/workspace
sudo chmod 755 "$currdir"/workspace/templates/php/bin/mysql/connect

rsync -avz "$currdir"/templates/* ~/.workspace/
rsync -avz "$currdir"/workspace ~/.workspace
ln -s ~/.workspace/workspace /usr/local/bin
cd $currdir/..
#rm -rf $currdir