#!/usr/bin/env bash

if [ ! -d ~/.workspace ]; then
    echo "Workspace not installed..."
    exit 1
elif [ ! -d ~/.workspace/"$lang" ]; then
    echo "No template found for $lang"
fi

builddir=$PWD

if [ -z $1 ]; then
    lang=php
else
    lang=$1
fi

if [ -z $2 ]; then
    echo "Building in current directory"
else
    echo "Building in $2"
    builddir=$builddir/$2
    mkdir "$builddir"
fi

if [ -d ~/.workspace/"$lang" ]; then
    cp -R ~/.workspace/"$lang"/* "$builddir"
fi
